### PR TITLE
fix console output

### LINKED ISSUE #75: abci-cli console produces empty output for some commands
https://tendermint.com/docs/guides/abci-cli

dummy app running in another process.

abci-cli console:

```
> echo hello
-> data: hello
-> data.hex: 68656C6C6F

> commit

> deliver_tx "abc"

> commit
-> data: u~׈$E
              -> data.hex: 750502FC7E84BBD788ED589624F06CFA871845D1

> query "abc"
-> log: exists
-> height: 0
-> value: abc
-> value.hex: 616263
```

both on master and develop https://github.com/tendermint/abci/commit/56e13d87f4e3ec1ea756957d6b23caa6ebcf0998

### PR DESCRIPTION
**Pull request by zramsay**
- closes #75, #93

### CODE REVIEW

File: cmd/abci-cli/abci-cli.go [hunk 1]
```diff
@@ -259,7 +259,7 @@ func cmdBatch(cmd *cobra.Command, args []string) {
 func cmdConsole(cmd *cobra.Command, args []string) {
 
 	for {
-		fmt.Printf("\n> ")
```
Comment (zramsay) [inline cmd/abci-cli/abci-cli.go]: the extra line is not necessary IMO and makes for a less nice experience because we end up with double line breaks

File: cmd/abci-cli/abci-cli.go [hunk 2]
```diff
@@ -454,12 +454,16 @@ func printResponse(cmd *cobra.Command, args []string, rsp response) {
 		fmt.Println(">", cmd.Use, strings.Join(args, " "))
 	}
 
-	if !rsp.Code.IsOK() {
-		fmt.Printf("-> code: %s\n", rsp.Code.String())
-	}
+	// Always print the status code.
```
Comment (zramsay) [inline cmd/abci-cli/abci-cli.go]: how the docs had it. it's a good verification that things worked

File: cmd/abci-cli/abci-cli.go [hunk 3]
```diff
@@ -454,12 +454,16 @@ func printResponse(cmd *cobra.Command, args []string, rsp response) {
...
+
 	if len(rsp.Data) != 0 {
-		fmt.Printf("-> data: %s\n", rsp.Data)
-		fmt.Printf("-> data.hex: %X\n", rsp.Data)
+		// Do no print this line when using the commit command
+		// because the string comes out as gibberish
+		if cmd.Use != "commit" {
+			fmt.Printf("-> data: %s\n", rsp.Data)
+		}
+		fmt.Printf("-> data.hex: 0x%X\n", rsp.Data)
```
Comment (zramsay) [inline cmd/abci-cli/abci-cli.go]: append 0x because that's how the docs are.

File: tests/test_cli/ex1.abci.out [hunk 4]
```diff
@@ -1,36 +1,44 @@
...
+-> code: OK
 
 > info 
+-> code: OK
 -> data: {"size":1}
--> data.hex: 7B2273697A65223A317D
+-> data.hex: 0x7B2273697A65223A317D
 
 > commit 
--> data: I��\ͬޮ�(���h����
```
Comment (zramsay) [inline tests/test_cli/ex1.abci.out]: uhmm, ya this was the test.
